In [99]:
!pip install pandas

In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [101]:
AND = pd.DataFrame({'x1': (0,0,1,1), 'x2': (0,1,0,1), 'y': (0,0,0,1)})
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [102]:
w = np.random.randn(3)*1e-4

In [103]:
g = lambda inputs, weights: np.where(np.dot(inputs, weights)>0, 1, 0)

In [104]:
print(w)
w.shape

[-1.68448223e-04  8.27794127e-05 -4.32228392e-05]


(3,)

In [105]:
##we are not using the sigmoid becoz the numerator will become very small and and the value tends to zero

"""def sigmoid(inputs,weights):
  z = np.dot(inputs,weights)
  values = 1/1+np.exp(-z)
  return values"""
  

'def sigmoid(inputs,weights):\n  z = np.dot(inputs,weights)\n  values = 1/1+np.exp(-z)\n  return values'

In [106]:
def train(inputs, targets, weights, eta, n_iterations):

    # Add the inputs that match the bias node
    inputs = np.c_[inputs, -np.ones((len(inputs), 1))]

    for n in range(n_iterations):

        print(f"Number of Epocs are {n}")
        print(inputs)
        activations = g(inputs, weights)
        print(activations)
        weights -= eta*np.dot(np.transpose(inputs), activations - targets)
        print(f"Weights are:{weights}")
    return weights


In [107]:
inputs = AND[['x1','x2']]
target = AND['y']
w = train(inputs, target, w, 0.1, 10)

Number of Epocs are 0
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[1 1 0 0]
Weights are:[9.98315518e-02 8.27794127e-05 9.99567772e-02]
Number of Epocs are 1
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 0]
Weights are:[ 1.99831552e-01  1.00082779e-01 -4.32228392e-05]
Number of Epocs are 2
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[1 1 1 1]
Weights are:[9.98315518e-02 8.27794127e-05 2.99956777e-01]
Number of Epocs are 3
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 0]
Weights are:[0.19983155 0.10008278 0.19995678]
Number of Epocs are 4
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
Weights are:[0.19983155 0.10008278 0.19995678]
Number of Epocs are 5
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
Weights are:[0.19983155 0.10008278 0.19995678]
Number of Epocs are 6
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
[0 0 0 1]
Weights are:[0.19983155 0.10